apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
  namespace: media
  labels:
    app: filebrowser
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      nodeSelector:
        kubernetes.io/hostname: atlantis # Pinned to the control plane
        
      securityContext:
        runAsUser: 0  # Runs as root so you can manage ALL files across arrays
        runAsGroup: 0
        
      containers:
      - name: filebrowser
        image: filebrowser/filebrowser:latest
        imagePullPolicy: Always
        
        # Configure Filebrowser using Environment Variables
        env:
          - name: FB_ADDRESS
            value: "0.0.0.0"
          - name: FB_PORT
            value: "80"
          - name: FB_DATABASE
            value: "/database/filebrowser.db"
            
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: storage-pool
          mountPath: /srv
        - name: fb-database
          mountPath: /database
          
      volumes:
      - name: storage-pool
        hostPath:
          path: /mnt # Mounts everything (nexus_pool, movies_pool, databoxes)
          type: Directory
      - name: fb-database
        hostPath:
          path: /mnt/internal/appdata/filebrowser
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: filebrowser-svc
  namespace: media
spec:
  type: NodePort
  selector:
    app: filebrowser
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30088
