apiVersion: apps/v1
kind: Deployment
metadata:
  name: trawl
  namespace: media
  labels:
    app: trawl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trawl
  template:
    metadata:
      labels:
        app: trawl
    spec:
      nodeSelector:
        kubernetes.io/hostname: avalon
      containers:
        - name: trawl
          image: ghcr.io/joshua-s/trawl:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "8080"
            - name: LOG_LEVEL
              value: "info"
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: trawl-data
              mountPath: /data
          resources:
            limits:
              cpu: "2"
              memory: 1536Mi
            requests:
              cpu: 200m
              memory: 256Mi
      volumes:
        - name: trawl-data
          persistentVolumeClaim:
            claimName: trawl-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: trawl-svc
  namespace: media
spec:
  type: ClusterIP
  selector:
    app: trawl
  ports:
    - name: http
      port: 8080
      targetPort: 8080
