apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr
  namespace: media
  labels:
    app: flaresolverr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaresolverr
  template:
    metadata:
      labels:
        app: flaresolverr
    spec:
      nodeSelector:
        kubernetes.io/hostname: phantom
      containers:
        - name: flaresolverr
          image: ghcr.io/flaresolverr/flaresolverr:latest
          env:
            - name: TZ
              value: "Asia/Kolkata"
            # THE FIX: Forces FlareSolverr to use the exact same VPN IP as Prowlarr
            - name: PROXY
              value: "http://qbittorrent-svc:8888"
          ports:
            - containerPort: 8191
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: flaresolverr-svc
  namespace: media
spec:
  selector:
    app: flaresolverr
  type: ClusterIP
  ports:
    - name: http
      port: 8191
      targetPort: 8191
