apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authentik-ingress
  namespace: security
spec:
  entryPoints: [web, websecure]
  routes:
    - match: Host(`auth.nexus.link`)
      kind: Rule
      services:
        - name: authentik-svc
          port: 9000
