apiVersion: v1
data:
  AUTHENTIK_POSTGRESQL__PASSWORD: UnBDcFVXbWZ1Z2NkMVlmR1hNVHc=
  AUTHENTIK_SECRET_KEY: RTZ6OENRSFZkQ0I5MG5kNVBVbmRRd205WnA0WHlpWE0=
  POSTGRES_PASSWORD: UnBDcFVXbWZ1Z2NkMVlmR1hNVHc=
kind: Secret
metadata:
  name: authentik-secret
  namespace: security
