apiVersion: v1
kind: PersistentVolume
metadata:
  name: authentik-postgres-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    server: 192.168.1.160
    path: /mnt/internal/appdata/authentik/postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-postgres-pvc
  namespace: security
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-storage
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: authentik-media-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    server: 192.168.1.160
    path: /mnt/internal/appdata/authentik/media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-media-pvc
  namespace: security
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage
  resources:
    requests:
      storage: 2Gi
