apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flaresolverr
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:alvish96/Elysium.git
    targetRevision: HEAD
    path: app-code/flaresolverr
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
