apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: browser-ingress
  namespace: media
spec:
  entryPoints: [web, websecure]
  routes:
    - match: Host(`browser.nexus.link`)
      kind: Rule
      middlewares: [{name: authentik-forwardauth, namespace: media}]
      services: [{name: browser-svc, port: 3001}]
