---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguardhome-sync
  namespace: networking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adguardhome-sync
  template:
    metadata:
      labels:
        app: adguardhome-sync
    spec:
      containers:
        - name: sync
          image: ghcr.io/bakito/adguardhome-sync:latest
          env:
            # Primary Source (Atlantis)
            - name: ORIGIN_URL
              value: "http://192.168.1.160:3000"
            - name: ORIGIN_USERNAME
              value: "admin"
            - name: ORIGIN_PASSWORD
              value: "YourAdguardPassword"
            
            # Replica 1 (Phantom)
            - name: REPLICA1_URL
              value: "http://192.168.1.170:3000"
            - name: REPLICA1_USERNAME
              value: "admin"
            - name: REPLICA1_PASSWORD
              value: "YourAdguardPassword"

            # Replica 2 (Olympus)
            - name: REPLICA2_URL
              value: "http://192.168.1.243:3000"
            - name: REPLICA2_USERNAME
              value: "admin"
            - name: REPLICA2_PASSWORD
              value: "YourAdguardPassword"

            # Sync Frequency (Every 10 Seconds)
            - name: CRON
              value: "*/10 * * * * *"
            - name: RUN_ON_START
              value: "true"
