---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguardhome-sync
  namespace: networking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adguardhome-sync
  template:
    metadata:
      labels:
        app: adguardhome-sync
    spec:
      containers:
        - name: sync
          image: ghcr.io/bakito/adguardhome-sync:latest
          env:
            # Origin Source (atlantis)
            - name: ORIGIN_URL
              value: "http://192.168.1.160:3000"
            - name: ORIGIN_USERNAME
              value: "admin"
            - name: ORIGIN_PASSWORD
              value: "adminlogin@123"
            
            # Secondary Replica (phantom)
            - name: REPLICA_URL
              value: "http://192.168.1.170:3000"
            - name: REPLICA_USERNAME
              value: "admin"
            - name: REPLICA_PASSWORD
              value: "adminlogin@123"

            # 5-field standard cron: Runs sync every 1 minute
            - name: CRON
              value: "*/1 * * * *"
            - name: RUN_ON_START
              value: "true"
