apiVersion: v1
kind: PersistentVolume
metadata:
  name: tdarr-server-data-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage-tdarr
  local:
    path: /mnt/internal/appdata/tdarr/server
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - atlantis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-server-data-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage-tdarr
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tdarr-configs-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage-tdarr
  local:
    path: /mnt/internal/appdata/tdarr/configs
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - atlantis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-configs-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage-tdarr
  resources:
    requests:
      storage: 5Gi
