apiVersion: v1
kind: PersistentVolume
metadata:
  name: homarr-local-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage-ssd
  local:
    path: /mnt/phantom_share/appdata/homarr
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - phantom
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homarr-local-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage-ssd
  resources:
    requests:
      storage: 5Gi
