apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homarr-ingress
  namespace: media
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`atlantis.fynbos-prometheus.ts.net`) && PathPrefix(`/`) || Host(`100.110.100.1`)
      kind: Rule
      priority: 1
      services:
        - name: homarr-svc
          port: 7575
