apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config-pv
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage-jellyfin
  local:
    path: /mnt/internal/appdata/jellyfin/config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - atlantis
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-nexus-pv
spec:
  capacity:
    storage: 10Ti
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage-jellyfin
  local:
    path: /mnt/nexus_pool
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - atlantis
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-phantom-pv
spec:
  capacity:
    storage: 200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage-jellyfin
  local:
    path: /mnt/phantom_nfs
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - atlantis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage-jellyfin
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-nexus-pvc
  namespace: media
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: local-storage-jellyfin
  resources:
    requests:
      storage: 10Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-phantom-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage-jellyfin
  resources:
    requests:
      storage: 100Gi
