apiVersion: apps/v1
kind: Deployment
metadata:
  name: apprise
  namespace: monitoring
  labels:
    app: apprise
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apprise
  template:
    metadata:
      labels:
        app: apprise
    spec:
      # Exclude Pi (32-bit ARM)
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                      - pi
      containers:
        - name: apprise
          image: lscr.io/linuxserver/apprise-api:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: "Asia/Kolkata"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            # --- DEFAULT DISCORD (AND TEAMS) WEBHOOKS ---
            - name: APPRISE_STATELESS_URLS
              value: "discord://1535861603948433508/a6beo5m8b15WvP5iOKTDNWepBK8Eb_ushJ61JPjkYfK9-veilu3JXUsYlg6qtu5iEqWu"
          ports:
            - containerPort: 8000
              name: http
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: apprise-svc
  namespace: monitoring
spec:
  type: ClusterIP
  selector:
    app: apprise
  ports:
    - port: 8000
      targetPort: 8000
      name: http
