apiVersion: v1
kind: PersistentVolume
metadata:
  name: homeassistant-config-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage-ha
  local:
    path: /mnt/phantom_share/appdata/homeassistant
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - phantom # Explicitly pins the storage to phantom's LVM disk
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-config-pvc
  namespace: homeassistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage-ha
  resources:
    requests:
      storage: 10Gi
