apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-config-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage-qbittorrent
  local:
    path: /mnt/internal/appdata/qbittorrent/config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - atlantis
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-data-pv
spec:
  capacity:
    storage: 10Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage-qbittorrent
  local:
    path: /mnt/nexus_pool/ # Unified structural anchor for atomic hardlinks
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - atlantis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage-qbittorrent
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-data-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage-qbittorrent
  resources:
    requests:
      storage: 10Ti
