apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyseerr-config-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-jellyseerr
  local:
    path: /mnt/internal/appdata/jellyseerr/config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - atlantis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyseerr-config-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual-jellyseerr
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyseerr
  namespace: media
  labels:
    app: jellyseerr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jellyseerr
  template:
    metadata:
      labels:
        app: jellyseerr
    spec:
      nodeSelector:
        kubernetes.io/hostname: atlantis

      dnsPolicy: ClusterFirst
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 1.1.1.1
        options:
          - name: ndots
            value: "1"

      securityContext:
        seccompProfile:
          type: Unconfined
        appArmorProfile:
          type: Unconfined

      containers:
        - name: jellyseerr
          image: lscr.io/linuxserver/jellyseerr:latest
          securityContext:
            allowPrivilegeEscalation: true
          env:
            - name: PUID
              value: "0"
            - name: PGID
              value: "0"
            - name: TZ
              value: "Asia/Kolkata"
          ports:
            - containerPort: 5055
              name: http
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: jellyseerr-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: jellyseerr-svc
  namespace: media
spec:
  selector:
    app: jellyseerr
  type: NodePort
  ports:
    - name: http
      port: 5055
      targetPort: 5055
      nodePort: 30555
