apiVersion: v1
kind: PersistentVolume
metadata:
  name: speedtest-tracker-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage-speedtest
  local:
    path: /mnt/internal/appdata/speedtest-tracker
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - avalon
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speedtest-tracker-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage-speedtest
  resources:
    requests:
      storage: 5Gi
