#!/usr/bin/env python3
import os
import subprocess
from pathlib import Path

# Repository root path
REPO_ROOT = Path(__file__).parent.parent.resolve()
APP_CODE = REPO_ROOT / "app-code"
ARGOCD_APPS = REPO_ROOT / "argocd-apps"
CONTEXT_DIR = REPO_ROOT / "context"

def run_cmd(cmd):
    """Utility to run terminal shell commands cleanly."""
    result = subprocess.run(cmd, shell=True, capture_output=True, text=True, cwd=REPO_ROOT)
    return result.stdout.strip()

def generate_state_md():
    """Scans app-code and argocd-apps to generate context/state.md."""
    apps = []
    
    if APP_CODE.exists():
        for app_dir in sorted(APP_CODE.glob("*")):
            if not app_dir.is_dir():
                continue
            
            app_name = app_dir.name
            argocd_wrapper = ARGOCD_APPS / f"{app_name}-app.yaml"
            wrapper_status = "✅ Present" if argocd_wrapper.exists() else "❌ Missing"
            
            namespaces = set()
            host_paths = set()
            ingresses = set()
            
            for yaml_file in app_dir.glob("*.yaml"):
                content = yaml_file.read_text(errors="ignore")
                for line in content.splitlines():
                    line_str = line.strip()
                    if line_str.startswith("namespace:"):
                        namespaces.add(line_str.split(":", 1)[1].strip())
                    if "path:" in line_str and ("/mnt/" in line_str or "/data" in line_str):
                        host_paths.add(line_str.split(":", 1)[1].strip())
                    if "host:" in line_str:
                        ingresses.add(line_str.split(":", 1)[1].strip().strip('"').strip("'"))

            apps.append({
                "name": app_name,
                "wrapper": wrapper_status,
                "namespace": ", ".join(namespaces) if namespaces else "default",
                "host_paths": ", ".join(host_paths) if host_paths else "None",
                "ingresses": ", ".join(ingresses) if ingresses else "None"
            })

    content = "# Elysium K3s Cluster: Live Manifest Inventory\n\n"
    content += "This file is automatically generated by `scripts/audit_agent.py`.\n\n"
    content += "| Application | ArgoCD Wrapper | Namespace | HostPath Mounts | Ingress Hostnames |\n"
    content += "| :--- | :--- | :--- | :--- | :--- |\n"
    for app in apps:
        content += f"| **{app['name']}** | {app['wrapper']} | `{app['namespace']}` | `{app['host_paths']}` | `{app['ingresses']}` |\n"
    
    (CONTEXT_DIR / "state.md").write_text(content)
    print(" [✓] Generated context/state.md")

def generate_context_md():
    """Generates context/context.md for quick AI prompt reference."""
    content = """# Elysium K3s Cluster Prompt Context

## Node Topology
- **atlantis** (`192.168.1.160`): Control Plane, Traefik Ingress, Authentik SSO, Core Databases, Storage Host.
- **olympus** (`192.168.1.243`): Compute Worker Node.
- **phantom** (`192.168.1.170`): Compute Worker Node.
- **pi** (`192.168.1.130`): Cordoned/Tainted (armv7l 32-bit architecture).

## Code Base Layout
- `app-code/`: Raw Kubernetes manifests organized per application.
- `argocd-apps/`: ArgoCD App-of-Apps wrapper definitions matching `app-code/` 1:1.
- `context/`: Source-of-truth files for AI guidance (`architecture.md`, `context.md`, `state.md`).

## Core Rules for AI Code Generation
1. Persistent data must map to `/mnt/internal/appdata/<app_name>` on `atlantis`.
2. Apply `seccompProfile: Unconfined` and `appArmorProfile: Unconfined` to PodSpecs for K8s 1.36+ compatibility.
3. Secrets are managed out-of-band in `~/Elysium-essentials/` (do not hardcode plain secrets).
4. Reference `cluster_ports.md` before binding hostPorts to avoid network collisions.
"""
    (CONTEXT_DIR / "context.md").write_text(content)
    print(" [✓] Generated context/context.md")

def generate_architecture_md():
    """Generates high-level structural blueprint in context/architecture.md."""
    content = """# Elysium K3s Cluster Architecture

## Structural Blueprint
- **GitOps Management:** ArgoCD App-of-Apps pattern using wrapper manifests in `argocd-apps/` targeting `app-code/`.
- **Ingress & Authentication:** Traefik Ingress Controller paired with Authentik ForwardAuth middlewares (`*.nexus.link`, `*.aura`).
- **Storage Strategy:** MergerFS volume pools (`/mnt/nexus_pool`) combined with persistent local appdata directories (`/mnt/internal/appdata/`).
- **Node Monitoring:** Glances DaemonSet, Netdata, Scrutiny (S.M.A.R.T.), and Beszel agents feeding hardware statistics back into `cluster-init/nodes/`.

## Non-Versioned Essentials Mapping
- `~/Elysium-essentials/RESTIC_MASTER_PASSWORD.txt` -> Backup encryption keys
- `~/Elysium-essentials/ai-secrets.yaml` -> LiteLLM / Open-WebUI API tokens
- `~/Elysium-essentials/argocd-repo-secret.yaml` -> ArgoCD SSH Key mapping
"""
    (CONTEXT_DIR / "architecture.md").write_text(content)
    print(" [✓] Generated context/architecture.md")

def sync_to_github():
    """Stages, commits, and pushes context files to GitHub."""
    print(" 🚀 Syncing files to GitHub...")
    run_cmd("git add context/architecture.md context/context.md context/state.md")
    
    status = run_cmd("git status --porcelain context/")
    if not status:
        print(" ℹ️ No documentation changes detected. Skipping git push.")
        return

    run_cmd('git commit -m "chore(audit): update context architecture, state, and context files"')
    push_output = run_cmd("git push origin main")
    print(" [✓] Successfully committed and pushed context files to GitHub!")

if __name__ == "__main__":
    CONTEXT_DIR.mkdir(exist_ok=True)
    print("🔍 Running Elysium Cluster Audit Agent...")
    generate_state_md()
    generate_context_md()
    generate_architecture_md()
    sync_to_github()
