apiVersion: v1
kind: PersistentVolume
metadata:
  name: beszel-hub-nfs-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-beszel
  nfs:
    server: 192.168.1.160
    path: /mnt/internal/appdata/beszel
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beszel-hub-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-beszel
  resources:
    requests:
      storage: 5Gi
